FROM node:18

# Install OpenSCAD
RUN apt-get update && apt-get install -y \
    openscad \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install PrusaSlicer
RUN curl -LO https://github.com/prusa3d/PrusaSlicer/releases/download/version_2.6.0/PrusaSlicer-2.6.0+linux-x64-202302231446.tar.bz2 \
    && tar -xjf PrusaSlicer-2.6.0+linux-x64-202302231446.tar.bz2 -C /opt \
    && rm PrusaSlicer-2.6.0+linux-x64-202302231446.tar.bz2 \
    && ln -s /opt/PrusaSlicer-2.6.0+linux-x64-202302231446/bin/prusa-slicer /usr/local/bin/prusa-slicer
# Create app directory
WORKDIR /app

# Copy package files and instal dependencies
COPY package*.json ./
RUN npm install

# Copy app source code 
COPY . .

# Create temp directory
RUN mkdir -p /app/temp && chmod 777 /app/temp

# Expose port
EXPOSE 3000

# Start the applicaiton
CMD [ "node", "server.js" ]